name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: install
      run: sudo apt-get install libevent-dev
    
    - name: make all
      run: make all
